In [19]:
import importlib
import bootstrap
import numpy as np
importlib.reload(bootstrap)

<module 'bootstrap' from '/home/feathernox/my_github_repositories/mipt-brainsignals/code/bootstrap.py'>

In [20]:
bootstrap.bootstrap(np.array([[0, 1], [0, 3], [1, 3]]), np.array([0, 1, 2]), len_sample=3)

[[2 2 0]]


IndexError: too many indices for array

In [ ]:
import numpy as np

from utils import check_random_state


class Bootstrap:
    def __init__(self, X, Y,
                 n_samples,
                 len_sample,
                 random_state=None):
        """
        Parameters
        ----------
        X, Y :

        n_samples :

        len_sample : 

        random_state : int, RandomState instance or None, optional (default=None)
            If int, random_state is the seed used by the random number generator;
            If RandomState instance, random_state is the random number generator;
            If None, the random number generator is the RandomState instance used
            by `np.random`.
        """
        self.n_samples = n_samples
        self.len_sample = len_sample
        self.X = np.array(X)
        self.Y = np.array(Y)
        self.sample_X = np.zeros((n_samples, len_sample, self.X.shape[1]))
        self.sample_Y = np.zeros((n_samples, len_sample, self.Y.shape[1]))
        for i in range(n_samples):
            idx = np.random.choice(np.arange(len(X)), len_sample, replace=True)
            self.sample_X[i] = self.X[idx]
            self.sample_Y[i] = self.Y[idx]

    def values(self):
        return self.sample_X, self.sample_Y


In [11]:
X = np.random.rand(5, 3)
print(X)
print(X[np.array([[1, 2], [3, 4]])])

[[ 0.60184635  0.18966185  0.56293612]
 [ 0.33881979  0.78085615  0.02563023]
 [ 0.40111048  0.9749335   0.78561814]
 [ 0.52479093  0.01264283  0.43093209]
 [ 0.8510325   0.539302    0.18532775]]
[[[ 0.33881979  0.78085615  0.02563023]
  [ 0.40111048  0.9749335   0.78561814]]

 [[ 0.52479093  0.01264283  0.43093209]
  [ 0.8510325   0.539302    0.18532775]]]


In [5]:
x = np.array([0, 1, 2, 4, 5])
class Some():
    pass

In [12]:
_check_features_mask(['a', 0])

ValueError: invalid literal for int() with base 10: 'a'

In [13]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'