In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2], [3, 5], [3, 4]])
np.linalg.svd(A)

(array([[-0.27826468, -0.5288777 , -0.80178373],
        [-0.72969345, -0.42641902,  0.53452248],
        [-0.62459286,  0.73379506, -0.26726124]]),
 array([ 7.98626929,  0.4685113 ]),
 array([[-0.54357341, -0.83936163],
        [ 0.83936163, -0.54357341]]))